# Generated by Django 2.2.1 on 2019-05-09 23:57

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190510_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='sign',
            field=models.ImageField(upload_to=catalog.models.image_folder),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Company'),
        ),
    ]
